# Example Manifest, to verify path health check grace period
# This manifest will endup continous restarts
# since the gracePeriodDelaySeconds > initialDelaySeconds
# HealthCheck gracePeriod == intialDelaySeonds
# This manifest also features failureThreshold, which can be used for maxFailures before pod gets killed
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-path-graceperiod
spec:
  containers:
  - name: liveness
    image: manojbadam/liveness
    env:
      - name: "GRACE_PERIOD_DELAY_SECONDS"
        value: "60"
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 1